= Partnership guidelines
:jbake-type: normalBase
:jbake-description: Host a BeJUG meeting.
:jbake-priority: 1.0
:showtitle:

The BeJUG is always looking for more partners that want to host one of our meetups.
This document describes what we are looking for.
We would love it if you drop us a message, either as a direct message https://www.meetup.com/belgian-java-user-group/[on Meetup.com] or though mail via <belgian (dot) jug (a) gmail (dot) com> if you are interested in hosting.

== What is the (BeJUG) ?

The primary focus of The Belgium Java User Group (founded in 1997 by Stephan Janssen) is to inform our members about the Java ecosystem.
We regularly organise sessions for Java and JVM interested developers, devops and teamleads to socialize, learn and inspire.

== What does a session look like?

At a BeJUG Meetup, usually one or two speakers give a talk about a Java-related topic.
Afterwards, informal mingling and socializing is a big aspect of the event.
Alternative sessions such as workshops, hackergardens and unconf-discussions are also possible, but not the main focus.

== What do we need from a Meetup Host?

To facilitate the Meetups, we need a place to gather.
We are looking for partners to provide us a location. Typically, these are companies with a JVM focussed development team.
A partner should be able to provide:

- (Required) A place for our speakers to present their session (beamer/screen, HDMI connection, internet)
- (Required) Enough room for our meetup members to gather (min 50, preferably more)
- (Optional) Drinks
- (Optional) Food

Additional aspects such as reachability and accessibility are a plus.

== What's in it for you as a host?

- We bring speakers to your company, which gives your employees the opportunity to learn from others outside "your bubble";
- Members of our meetup will visit the location you provide, which associates your company with being an active member of the Java Community;
- A big thank you during the introduction and ending of the event by a member of the BeJUG organisation;
- When announcing the event and in all communication about the event afterwards, your company name will be included in the announcement (with social links @PARTNER_NAME);

We believe the above provides a lot of value to you as a host.

== What does Belgium JUG do?

We act as organizers. We:

- Search and invite the speakers and create a program for the event: these are occasionally top speakers you could find at conferences but we do give plenty of opportunities to lesser known speakers! The exact speakers which speak at an event are at our discretion and can be changed when needed;
- Setup the invite mailing and registration form: we use Meetup.com for this;
- Promote the event on our social media channels.

== What are some other aspects a prospective partner should know about?

- The Meetup is organized as a "Belgian Java User Group"-event, not a "<PARTNER_NAME> event";
- All attendees must register through the Meetup group. This helps us to expand the group and gives structure to the signup process;
- As a default, we do not allow employees of the hosting company to present a full session that same evening. Exceptions may be made due to planning constraints;
- For historical reasons and to not give a company any preferential treatment, we do not leave room for the hosting company to introduce themselves or present any sort of "promo" talk for the company;
- After the event is announced on the official BeJUG channels, the host will receive a set of links (1 for each platform) so they can retweet/repost/share among their own network. 
